version: '3.8'

services:
  api:
    build: .
    ports:
      - '8090:8090'
    container_name: vaccination-center-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BaseDeDonnees
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=987654321
    links:
      - 'db:BaseDeDonnees'
  db:
    image: postgres:15.2
    restart: always
    container_name: vaccination-center-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 987654321
      POSTGRES_DB: BaseDeDonnees
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "6432:5432"
volumes:
  db-data:
    driver: local